<?xml version="1.0" encoding="utf-8"?>
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/main"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:background="#FFEE96">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center"
        android:id="@+id/layout_First_Page"
        android:visibility="visible"
        android:orientation="vertical">

        <Button
            android:id="@+id/btn_Start"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_margin="120dp"
            android:backgroundTint="#F15F5F"
            android:text="START" />
    </LinearLayout>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/layout_InGame"
        android:visibility="invisible"
        android:orientation="vertical"
        >

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal"
            android:layout_gravity="top"
            android:gravity="end"
            android:background="#AAFFA3">
            <TextView
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:layout_marginStart="10dp"
                android:textSize="15dp"
                android:id="@+id/TimeDisplay"
                />
            <Button
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginEnd="5dp"
                android:id="@+id/btn_InGame_Setting"
                android:backgroundTint="#F15F5F"
                android:text="setting"
                >
            </Button>
        </LinearLayout>
        <FrameLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:id="@+id/inGame_play"
            >
            <GridLayout
                android:id="@+id/inGame_field"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:columnCount="7"
                android:padding="16dp"
                android:rowCount="14"
                />
        </FrameLayout>
    </LinearLayout>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center"
        android:id="@+id/layout_SettingPage"
        android:visibility="invisible"
        android:background="#99ffffff"
        android:orientation="vertical"
        android:clickable="true"
        android:focusable="true">
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">
            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginHorizontal="110dp"
                android:textSize="30dp"
                android:text="Volume"/>
            <CheckBox
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginHorizontal="120dp"
                android:id="@+id/Mute"
                android:text="Mute"
                android:textSize="20dp"
                />
            <SeekBar
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:id="@+id/VolumeControl"
                android:max="100"
                android:progress="50"
                android:layout_marginBottom="30dp"
                android:layout_marginHorizontal="100dp"
                />
        </LinearLayout>

        <Button
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:id="@+id/btn_SettingPage_Back"
            android:backgroundTint="#F15F5F"
            android:layout_marginHorizontal="120dp"
            android:text="Back"
            />
        <Button
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:id="@+id/btn_SettingPage_Restart"
            android:backgroundTint="#F15F5F"
            android:layout_marginHorizontal="120dp"
            android:text="Restart"
            />
        <Button
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:id="@+id/btn_SettingPage_Title"
            android:backgroundTint="#F15F5F"
            android:layout_marginHorizontal="120dp"
            android:text="Title"
            />
    </LinearLayout>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/layout_EndPage"
        android:visibility="invisible"
        android:background="#99ffffff"
        android:orientation="vertical"
        android:gravity="center"
        android:clickable="true"
        android:focusable="true">
        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textSize="50dp"
            android:text="Score"/>
        <Button
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:id="@+id/btn_EndPage_Again"
            android:backgroundTint="#F15F5F"
            android:layout_marginHorizontal="120dp"
            android:text="Again"
            />
        <Button
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:id="@+id/btn_EndPage_Title"
            android:backgroundTint="#F15F5F"
            android:layout_marginHorizontal="120dp"
            android:text="Title"
            />
    </LinearLayout>


</FrameLayout>
